services:
  - type: web
    name: AEDDI_backend
    env: php
    buildCommand: "composer install"
    startCommand: "php artisan serve --host=0.0.0.0 --port=8080"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: "base64:YOUR_APP_KEY"
