services:
  - type: web
    name: AEDDI-backend
    env: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    buildContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ton-hôte-mysql.render.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: nom_de_ta_db
      - key: DB_USERNAME
        value: ton_utilisateur
      - key: DB_PASSWORD
        sync: false
